/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parsed_vision.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "parsed_vision.pb-c.h"
void   robot__init
                     (Robot         *message)
{
  static const Robot init_value = ROBOT__INIT;
  *message = init_value;
}
size_t robot__get_packed_size
                     (const Robot *message)
{
  assert(message->base.descriptor == &robot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot__pack
                     (const Robot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot__pack_to_buffer
                     (const Robot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Robot *
       robot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Robot *)
     protobuf_c_message_unpack (&robot__descriptor,
                                allocator, len, data);
}
void   robot__free_unpacked
                     (Robot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ball__init
                     (Ball         *message)
{
  static const Ball init_value = BALL__INIT;
  *message = init_value;
}
size_t ball__get_packed_size
                     (const Ball *message)
{
  assert(message->base.descriptor == &ball__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ball__pack
                     (const Ball *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ball__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ball__pack_to_buffer
                     (const Ball *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ball__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ball *
       ball__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ball *)
     protobuf_c_message_unpack (&ball__descriptor,
                                allocator, len, data);
}
void   ball__free_unpacked
                     (Ball *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ball__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   parsed_frame__init
                     (ParsedFrame         *message)
{
  static const ParsedFrame init_value = PARSED_FRAME__INIT;
  *message = init_value;
}
size_t parsed_frame__get_packed_size
                     (const ParsedFrame *message)
{
  assert(message->base.descriptor == &parsed_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parsed_frame__pack
                     (const ParsedFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parsed_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parsed_frame__pack_to_buffer
                     (const ParsedFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parsed_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ParsedFrame *
       parsed_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ParsedFrame *)
     protobuf_c_message_unpack (&parsed_frame__descriptor,
                                allocator, len, data);
}
void   parsed_frame__free_unpacked
                     (ParsedFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &parsed_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor robot__field_descriptors[3] =
{
  {
    "robot_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Robot, robot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot, pos),
    &vector3_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot, vel),
    &vector3_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot__field_indices_by_name[] = {
  1,   /* field[1] = pos */
  0,   /* field[0] = robot_id */
  2,   /* field[2] = vel */
};
static const ProtobufCIntRange robot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor robot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Robot",
  "Robot",
  "Robot",
  "",
  sizeof(Robot),
  3,
  robot__field_descriptors,
  robot__field_indices_by_name,
  1,  robot__number_ranges,
  (ProtobufCMessageInit) robot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ball__field_descriptors[2] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ball, pos),
    &vector2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ball, vel),
    &vector2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ball__field_indices_by_name[] = {
  0,   /* field[0] = pos */
  1,   /* field[1] = vel */
};
static const ProtobufCIntRange ball__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ball__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ball",
  "Ball",
  "Ball",
  "",
  sizeof(Ball),
  2,
  ball__field_descriptors,
  ball__field_indices_by_name,
  1,  ball__number_ranges,
  (ProtobufCMessageInit) ball__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor parsed_frame__field_descriptors[2] =
{
  {
    "robots",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ParsedFrame, n_robots),
    offsetof(ParsedFrame, robots),
    &robot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ball",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ParsedFrame, ball),
    &ball__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parsed_frame__field_indices_by_name[] = {
  1,   /* field[1] = ball */
  0,   /* field[0] = robots */
};
static const ProtobufCIntRange parsed_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parsed_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ParsedFrame",
  "ParsedFrame",
  "ParsedFrame",
  "",
  sizeof(ParsedFrame),
  2,
  parsed_frame__field_descriptors,
  parsed_frame__field_indices_by_name,
  1,  parsed_frame__number_ranges,
  (ProtobufCMessageInit) parsed_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
