/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: robot_action.proto */

#ifndef PROTOBUF_C_robot_5faction_2eproto__INCLUDED
#define PROTOBUF_C_robot_5faction_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Command Command;
typedef struct Vector3D Vector3D;
typedef struct Vector2D Vector2D;


/* --- enums --- */

/*
 * Enum for different types of actions
 */
typedef enum _ActionType {
  ACTION_TYPE__KICK_ACTION = 0,
  ACTION_TYPE__STOP_ACTION = 1,
  ACTION_TYPE__MOVE_TO_ACTION = 2,
  ACTION_TYPE__INIT_ACTION = 3,
  ACTION_TYPE__MOVE_ACTION = 4,
  ACTION_TYPE__ROTATE_ACTION = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ACTION_TYPE)
} ActionType;

/* --- messages --- */

struct  Command
{
  ProtobufCMessage base;
  ActionType command_id;
  int32_t robot_id;
  int32_t kick_speed;
  Vector3D *pos;
  Vector3D *dest;
  Vector2D *direction;
  /*
   * Negative value rotates robot clockwise
   */
  int32_t angular_vel;
};
#define COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&command__descriptor) \
    , ACTION_TYPE__KICK_ACTION, 0, 0, NULL, NULL, NULL, 0 }


/*
 * Structure for 3D vector
 */
struct  Vector3D
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  float w;
};
#define VECTOR3_D__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vector3_d__descriptor) \
    , 0, 0, 0 }


/*
 * Structure for 2D vector
 */
struct  Vector2D
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
};
#define VECTOR2_D__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vector2_d__descriptor) \
    , 0, 0 }


/* Command methods */
void   command__init
                     (Command         *message);
size_t command__get_packed_size
                     (const Command   *message);
size_t command__pack
                     (const Command   *message,
                      uint8_t             *out);
size_t command__pack_to_buffer
                     (const Command   *message,
                      ProtobufCBuffer     *buffer);
Command *
       command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   command__free_unpacked
                     (Command *message,
                      ProtobufCAllocator *allocator);
/* Vector3D methods */
void   vector3_d__init
                     (Vector3D         *message);
size_t vector3_d__get_packed_size
                     (const Vector3D   *message);
size_t vector3_d__pack
                     (const Vector3D   *message,
                      uint8_t             *out);
size_t vector3_d__pack_to_buffer
                     (const Vector3D   *message,
                      ProtobufCBuffer     *buffer);
Vector3D *
       vector3_d__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vector3_d__free_unpacked
                     (Vector3D *message,
                      ProtobufCAllocator *allocator);
/* Vector2D methods */
void   vector2_d__init
                     (Vector2D         *message);
size_t vector2_d__get_packed_size
                     (const Vector2D   *message);
size_t vector2_d__pack
                     (const Vector2D   *message,
                      uint8_t             *out);
size_t vector2_d__pack_to_buffer
                     (const Vector2D   *message,
                      ProtobufCBuffer     *buffer);
Vector2D *
       vector2_d__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vector2_d__free_unpacked
                     (Vector2D *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Command_Closure)
                 (const Command *message,
                  void *closure_data);
typedef void (*Vector3D_Closure)
                 (const Vector3D *message,
                  void *closure_data);
typedef void (*Vector2D_Closure)
                 (const Vector2D *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    action_type__descriptor;
extern const ProtobufCMessageDescriptor command__descriptor;
extern const ProtobufCMessageDescriptor vector3_d__descriptor;
extern const ProtobufCMessageDescriptor vector2_d__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_robot_5faction_2eproto__INCLUDED */
