/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "robot_action.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)


PB_BIND(Vector3D, Vector3D, AUTO)


PB_BIND(Vector2D, Vector2D, AUTO)




